### ISSUE TITLE
High-hash errors

### ISSUE THREAD

**Issue by mikebutrimov** [CryptoManiac/eloipool-scrypt#2]
Hello. During my experiments with eloipool-scrypt i get a lot of different errors and a lot of misunderstanding.
First of all, thank you for your job, but can you explain the high-hash problem.
While working on testnet, i have a lot of high-hash errors. The look like:
 Rejected 13aa67f0 Diff 13/1 GPU 0 pool 4 (high-hash) 
 Rejected 19b66575 Diff 9/1 GPU 0 pool 4 (high-hash)  
and so on. 
i started my investigations with source code studying.
"if blkhashn > workTarget:
                print ('blkhashn: %s'%blkhashn)
                raise RejectedShare('high-hash')
"
ok, it is clear.
But, when i output blkhashn and worktarget values i get some kind of misunderstanding. 
usually worktarget is much less than blkhashn.
"blkhashn: 115240590068926395824544195963645551740562364790969455860590670520275896758640
worktarget: 27606985387162255149739023449108101809804435888681546220650096895197183
"

i go deeper into source code and create some debug output of different wariables, such as networktarget and worktarget and blkhash. here it is:
http://pastebin.com/nDnpDQgv
Also new blocks faild with high-hash error, and in litecoin debug log it looks like:
"ERROR: CheckProofOfWork() : hash doesn't match nBits
ERROR: CheckBlock() : proof of work failed
ERROR: ProcessBlock() : CheckBlock FAILED
"
So what goes wrong? maybe it is some kind of erroneous configuration? 
ShareTarget = 0x0000ffff00000000000000000000000000000000000000000000000000000000
DynamicTargetting = 2
DynamicTargetGoal = 8
DynamicTargetWindow = 300

Sometimes testnet accepted one of the fifty blocks. But it is the exception rather than normal situation.

**Comment by CryptoManiac** [comment]
Hi. "high-hash" error means that the result of scrypt(header) doesn't satisfy the current share target. That could be caused by mining sortware errors or hardware misconfiguration.

By the way, ltcmine and give-me-ltc runs this software currently.

**Comment by CryptoManiac** [comment]
Publish your miner options, please.

**Comment by ghost** [comment]
I would think it's the miner too. Maybe you're pushing your GPU to hard (intensity set too high?). During my tests with Pooler's CPU miner I had no high hash errors at all.

**Comment by mikebutrimov** [comment]
I tried to collect all information, that probably is needed for debugging. here it is:
I'm using to mining rigs. First one is my test rig, it contains only one Core i5 CPU and runs under GNU/Linux. 
for mining cgminer 3.3.0 with scrypt support is used. 
this is log of an high-hash error, that occurs during mining:
http://pastebin.com/ZKxa1T1g

No kind of overclocking is used, it is ordinary PC.
It generates shares very slowly, but every time it happens, share is rejected with high-hash error.   

Another rig is quite powerful.
It runs under win 7 and cgminer 3.2.2 It is property of my chief, but he grant me access to perform my tests.
It contains some radeon overclocked chips, all works right on differnt pools,  but not on mine. 
Logs from this rig:
http://pastebin.com/jMTmHyBp
Sometimes it founds a block. Average blocks per hour in testnet is about 3 blocks per hour that have been accepted.
It is very strange. On other pools there is maybe one high-hash error on 99 accepted shares, but not 100 high-hash rejects on 100 shares. 

I also configured pushpool for tests and here is the result:
http://pastebin.com/U96WV2mL

It solves 2 blocks in few minutes and high-hash errors level is low.
Switching back to eloipool and high-hash errors come back. 
What shall i do now? I can collect another debug information or performe some other different tests.
My be something goes wrong between eloipool and litecoind?
If it is important, information about litecoind:
"...litecoin/litecoin-0.8.3.7-linux/bin/64/litecoind getinfo
{
    "version" : 80307,
    "protocolversion" : 70002,
    "walletversion" : 60000,

<...>
"
I am very intrested in finding solution. 
Best regards, Mike.

**Comment by CryptoManiac** [comment]
```
My be something goes wrong between eloipool and litecoind?
```

According to published log, eloipool received a share with greater hash than required. 

Try to start this with the production network, and see what will happen. This daemon never checked with testnet before, only with production network (ltcmine.ru for a year and give-me-ltc for a few months).

I'll try in testnet later. But I don't think that we will find any difference here, except for magic bytes.

**Comment by mikebutrimov** [comment]
results from production network:
log from miner:
http://pastebin.com/zLuw2XSA
Pool 4 is eloipool with longpoll 
Pool 5 is the same eloipool with stratum

eloipool config:
http://pastebin.com/S9cKMNHX

What else can I do to clear up the situation?

**Comment by ghost** [comment]
3 things I notice in your eloipool config:

1) You are using a truncated value for ShareTarget. Better use: 0x0000ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
2) where is the UpstreamNetworkId in your config? It should have UpstreamNetworkId = b'\xFB\xC0\xB6\xDB' for litecoin
3) You are using port 8333 as the json rpc port. Default port for litecoin is 9333. Are you sure you're not connecting to your bitcoin client?

**Comment by mikebutrimov** [comment]
1) "You are using a truncated value for ShareTarget. Better use: 0x0000ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff" - done.
2) UpstreamNetworkId is in config file, but it was accidentally cuted out, when i removed all comments from the config file by using sed. 
3) It is rpc port, using to connect eloipool to litecoind, isn't it? i guess it does not matters what it is. 9333 (19333 for testnet) is using to connect litecoind to the network. 
now config (with all comments) is:
http://pastebin.com/YRv25aHz

result in production net is still "high-hashing"
http://pastebin.com/Wc3ydZKm

**Comment by ghost** [comment]
config looks good now.

You could insert the line 'print(rv)' into the file jsonrpc_getwork.py. at line 69, between
self._JSONHeaders...
and
return rv

this will print the actual getWork response sent by the JSONrpc server to you miner.

it should look something like this:
{'hash1': '00000000000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000010000', 'data': '00000002686cd060d875fe41cd5c2fc17000b85cbe1806bf05781e977112f3eabe41a4c21b6b45ee615b05b4c07cb73b82c66747311759b17301bff76599a29a2ddc26fd5224b9041d025aca456c6f69000000800000000000000000000000000000000000000000000000000000000000000000000000000000000080020000', 'target': 'ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff0000'

Where the value for 'target' should match whatever you have set in the config file (only then reversed like above).

**Comment by CryptoManiac** [comment]
mikebutrimov, try to register here

http://ltcmine.ru

Create worker and point your miner to stratum+tcp://ltcmine.ru:3334. Let's see how is it. 

P.S. Stats is currently frozen, but it doesn't matter for our tests.

**Comment by mikebutrimov** [comment]
Hmmm. Smth strange. I add two lines (http://pastebin.com/Wzn927sb):
    43                  print ("Getwork got control") (to see, when getwork actually takes control)
and
 70                  print(rv) (as you recommend to see debug output of rv var)

and there is nothing in the console. I guess, getwork must be called everytime when new block had been recived, but if this occurs, there is nothing in the console: http://pastebin.com/L1aQDKxa

**Comment by CryptoManiac** [comment]
```
I guess, getwork must be called everytime when new block had been recived
```

jsonrpc_getwork is a getwork() RPC handler. This function called every time when legacy miner sends request for the new work from server, or sends the work result.

If you are using cgminer then I guess that it works using getblocktemplate() RPC call. There are a few options for your situation:
- You can disable getblocktemplate support in your miner;
- You can disable getblocktemplate support in eloipool;
- You can edit jsonrpc_getblocktemplate file instead of jsonrpc_getwork.

**Comment by mikebutrimov** [comment]
here results from ltcmine.ru
http://pastebin.com/BJWwL1MT
looks like all works well

**Comment by CryptoManiac** [comment]
That's strange, because this repository is exact copy of ltcmine software...

**Comment by mikebutrimov** [comment]
may it depend on os/python version ? can i collect any else information, usefull for debugging?

**Comment by mikebutrimov** [comment]
if it important, pool OS info:
uname -ar
Linux pool.****\* 2.6.32-358.11.1.el6.x86_64 #1 SMP Wed Jun 12 03:34:52 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
python3 --version
Python 3.2.5

Python was build from sources.

**Comment by mikebutrimov** [comment]
maybe endianness is different in some libs / architecture?

**Comment by mikebutrimov** [comment]
edited jsonrpc_getblocktemplate. 
Result:
"
{'previousblockhash': 'b91ab7dde5f1e71c1216f0dbc8cde037ab7e355b5696afe4ad3fd7f158008de9', 'target': '000007ffffffffffffffffffffffffffffffffffffffffffffffffffffffffff', 'noncerange': '00000000ffffffff', 'transactions': [], 'mintime': 1378301012, 'sigoplimit': 20000, 'expires': 120, 'longpoll': '/LP', 'height': 86351, 'coinbasetxn': {'data': '01000000010000000000000000000000000000000000000000000000000000000000000000ffffffff09034f51010452273508ffffffff0100f2052a010000001976a914ff1c0aaf3f6b48d730a8efc5c25fe294635b506888ac00000000'}, 'version': 2, 'time': 1378301192, 'curtime': 1378301192, 'mutable': ['coinbase/append', 'submit/coinbase'], 'sizelimit': 1000000, 'maxtime': 1378301312, 'longpollid': '1378301188 3', 'bits': '1e01e2d8'}
"

**Comment by mikebutrimov** [comment]
print (rv) in the beginning and end of the doJSON_getblocktemplate in the jsonrpc_getblocktemplate.py:
http://pastebin.com/3SzZQF58

**Comment by CryptoManiac** [comment]
mikebutrimov

```
may it depend on os/python version ? can i collect any else information, usefull for debugging?
```

I'm running AMD64 build of Debian GNU/Linux Squeeze with python3 packages from repository. Hardware configuration:

2 x Intel Xeon E5645
32Gb of RAM

```
Linux ltcmine.ru 2.6.32-5-amd64 #1 SMP Mon Feb 25 00:26:11 UTC 2013 x86_64 GNU/Linux
```

```
Python 3.1.3 (r313:86834, Nov 28 2010, 10:01:07)
[GCC 4.4.5] on linux2
```

```
root@ltcmine:~# gcc -v
Using built-in specs.
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 4.4.5-8' --with-bugurl=file:///usr/share/doc/gcc-4.4/README.Bugs --enable-languages=c,c++,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.4 --enable-shared --enable-multiarch --enable-linker-build-id --with-system-zlib --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.4 --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-objc-gc --with-arch-32=i586 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.4.5 (Debian 4.4.5-8)
root@ltcmine:~#
```

**Comment by mikebutrimov** [comment]
is that correct getblock? http://pastebin.com/3SzZQF58

**Comment by CryptoManiac** [comment]
It's getblocktemplate output. Yep, it's correct. Can you provide submission results?

--protocol-dump option should help getting this data.

**Comment by mikebutrimov** [comment]
which of them (eloipool, cgminer or bitcoind) does have this option? Or tcp dump of traffic between eloipool and litecoind is needed? all of them accept this option, but output does not changes.
here are results on production net:
console of eloipool with getwork outout enabled:
http://pastebin.com/2J34rvge

debug log of litecoind:
http://pastebin.com/UCqBKXt2

lof of cgminer:
http://pastebin.com/2BevBttW

**Comment by CryptoManiac** [comment]
It's cgminer option. Allows you to see low-level communication between miner and daemon.

**Comment by mikebutrimov** [comment]
i use --verbose and -P with cgminer and there is output:
http://pastebin.com/7Eu1qvPb

is it correct? Does it gives something to us?

**Comment by CryptoManiac** [comment]
Normal log, except for 100% rejects of course. Try this

 --scrypt  --sharelog share.log -o xxx -u yyy -p zzz

By the way, why it hashes so slow? I guess that 1.780Kh/s is too lottle even for nvidia. My Atom D512 able to hash at 5-6 khash/s.

**Comment by mikebutrimov** [comment]
cgminer log:
http://pastebin.com/6NaPw0TP
share.log:
http://pastebin.com/YSFK76KD
eloipool console log with getwork output:
http://pastebin.com/iJkjFXA9

Does it looks strange in share log: "hash,ffffffffffffffffffffffffffffffffffffffffffffffffffffffffff0f0000," ?
i mean strange  zero between  f anf f

**Comment by TTcoinDeveloper** [comment]
ok so I was streaming through the bitcoin source code and I found this
SOLO miners his applies to any coin

Code:
    // Check proof of work matches claimed amount
    if (fCheckPOW && !CheckProofOfWork(block.GetHash(), block.nBits))
        return state.DoS(50, error("CheckBlockHeader() : proof of work failed"),
                         REJECT_INVALID, "high-hash");

which means that this is the reason for that particular error
this simply means that your proof of work does not match the claimed amount

I suggest you update your wallet , I am not to familiar with the roadmap of the coin you are mining but at the point where you downloaded the wallet to the time mining begins with the coin..... mining may have been disabled then with your wallet and enabled now with an updated release
or get 1 with compatible python miner and plz ensure the coin you are planning to mine or mining is GPU compatible and no CPU only
