### ISSUE TITLE
No Worker Authorization

### ISSUE THREAD

**Issue by ahmedbodi** [CryptoManiac/eloipool-scrypt#3]
It doesnt look like this authorizes workers using simplefile like luke-jr's eloipool does

**Comment by CryptoManiac** [comment]
You are right, it's based on old eloipool snapshot. Will merge new features soon.

**Comment by ahmedbodi** [comment]
ive added in a pull request to add in the authentication the same way Luke-Jr has done it to sha eloipool if you would like to test it and then merge it
