### ISSUE TITLE
block solution not recognized in frontend

### ISSUE THREAD

**Issue by Neozonz** [CryptoManiac/eloipool-scrypt#5]
https://github.com/TheSerapher/php-mmcfe-ng/blob/next/public/include/classes/share.class.php#L243-L316

How can we format solution in order to be accepted via mmcfe-ng?

**Comment by Neozonz** [comment]
I've attempted to match the solution formatting to mmcfe-ng but the hash's are always different... any help would be appreciated

**Comment by ahmedbodi** [comment]
Try copying the solution formatting from my sha eloipool and seeing if it works

**Comment by Neozonz** [comment]
It seems to the the same as the original?

share['solution'] = b2a_hex(swap32(share['data'])).decode('utf8')
