### ISSUE TITLE
UpstreamNetworkId for other scrypt based coins

### ISSUE THREAD

**Issue by ppanther1000** [CryptoManiac/eloipool-scrypt#6]
Does anybody have UpstreamNetworkIds working correctly with eloipool-scrypt for dogecoin, worldcoin and anoncoin?

**Comment by CryptoManiac** [comment]
You can find it in the *coind sources. But don't try to do it, because that won't work. Eloipool merklemaker module contains a reward calculation code which should be modified to work properly with another coins.
